# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a630eaf8119a07166e8e7981461805937dfd5c7d8dd060e51a001e942dcc141983faa82a547eeb9f2de2987494e436fe8f65ef3dec2c481b2d0363d8827746f

test:
  secret_key_base: 60520d1d4083f647ae0047a5ecfbd9fecbb9ef99f93a538cc0cf2e1da09eb42bdb54e913c2683c722e8ba166428c92f741fc26fcffb76478968ca80e07718496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
